project:
  type: website
  output-dir: docs

website:
  title: "Cormufave"
  back-to-top-navigation: true    
  navbar:
    title: false
    background: transparent
    pinned: true
    search: false
    right:
      - text: "![Español](images/co.svg){width=30}"
        href: "index.qmd"
      - text: "![English](images/gb.svg){width=30}"
        href: "index.qmd"
  page-footer:
    background: "#1b802c"
    center:
    - text: "© CORMUFAVE, Corporación Mujeres y Familia El Vergel •"
    - icon: instagram
      href: "https://www.instagram.com/mujeresyfamilia.vergel"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    lang: es
    include-after-body:
      - text: |
          <script async src="//www.instagram.com/embed.js"></script>
