project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Cormufave"
  back-to-top-navigation: false    
  navbar:
    title: false
    background: transparent
    pinned: true
    search: false
    right:
      - text: "<img src='images/co.svg' style='width:30px; border-radius:0px;'>"
        href: "index.qmd"
      - text: "<img src='images/gb.svg' style='width:30px; border-radius:0px;'>"
        href: "index-en.qmd"
  page-footer:
    background: "#124a06"
    center:
    - text: "© CORMUFAVE, Corporación Mujeres y Familia El Vergel •"
    - icon: instagram
      href: "https://www.instagram.com/mujeresyfamilia.vergel"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: false
    lang: es
    include-after-body:
      - text: |
          <script async src="//www.instagram.com/embed.js"></script>
